# Generated by Django 6.0.3 on 2026-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=200)),
                ('flight_name', models.CharField(max_length=500)),
                ('flight_no', models.IntegerField()),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
